
package org.example;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param id
     * @return
     *     returns org.example.Person
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://example.org/", className = "org.example.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://example.org/", className = "org.example.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @param name
     * @param id
     * @param age
     * @return
     *     returns org.example.Person
     * @throws PersonExistsEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://example.org/", className = "org.example.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://example.org/", className = "org.example.AddPersonResponse")
    public Person addPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age)
        throws PersonExistsEx_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://example.org/", className = "org.example.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://example.org/", className = "org.example.DeletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @param name
     * @param id
     * @param age
     * @return
     *     returns org.example.Person
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://example.org/", className = "org.example.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://example.org/", className = "org.example.UpdatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countPersons", targetNamespace = "http://example.org/", className = "org.example.CountPersons")
    @ResponseWrapper(localName = "countPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.CountPersonsResponse")
    public int countPersons();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearPersons", targetNamespace = "http://example.org/", className = "org.example.ClearPersons")
    @ResponseWrapper(localName = "clearPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.ClearPersonsResponse")
    public boolean clearPersons();

    /**
     * 
     * @return
     *     returns java.util.List<org.example.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://example.org/", className = "org.example.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.GetAllPersonsResponse")
    public List<Person> getAllPersons();

}
